# Generated by Django 3.2.18 on 2024-06-21 08:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVotingApp', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='constituency',
            name='status',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='party',
            name='status',
            field=models.IntegerField(default=1),
        ),
    ]
