# Generated by Django 3.2.18 on 2024-12-03 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVotingApp', '0002_auto_20240621_1417'),
    ]

    operations = [
        migrations.AddField(
            model_name='party',
            name='logo',
            field=models.ImageField(blank=True, null=True, upload_to='party/'),
        ),
    ]
