# Generated by Django 3.2.18 on 2024-12-03 05:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVotingApp', '0003_party_logo'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='voter_id',
            field=models.CharField(default=1, max_length=15),
            preserve_default=False,
        ),
    ]
