# Generated by Django 3.2.18 on 2024-12-03 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('EVotingApp', '0004_user_voter_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='voter_id',
            field=models.CharField(max_length=15, unique=True),
        ),
    ]
